# Generated by Django 5.1.4 on 2025-04-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('top_key_freq', models.TextField(blank=True, null=True)),
                ('tokens', models.TextField(blank=True, null=True)),
                ('tokens_v2', models.TextField(blank=True, null=True)),
                ('entities', models.TextField(blank=True, null=True)),
                ('token_pos', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('photo_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_data',
            },
        ),
    ]
